/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airasysad;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javafx.scene.control.DatePicker;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author takajima
 */
public class Input extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ArrayList<String> ppID = new ArrayList<String>();

    //Date Picker SYSTEM -------
    int month = java.util.Calendar.getInstance().get(java.util.Calendar.MONTH);
    int year = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    JLabel l = new JLabel("", JLabel.CENTER);  
    String day = "";
    JDialog d;
    JButton[] button = new JButton[49];

    /**
     * Creates new form Input
     */
    public Input() {
        initComponents();
        conn = database.sqliteConnect.connectorDB();
        FillUpdateProductCategoryName();
        int month = java.util.Calendar.getInstance().get(java.util.Calendar.MONTH);
        int year = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
        
Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    private void FillUpdateProductCategoryName() {
        try {
            String sqlQuery = "SELECT Product from BlueBees";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            while (rs.next()) {
                String cat = rs.getString("Product");
                if (cat != null) {
                    Product.addItem(cat);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

///DATE PICKER SYSTEM-----------------------------------------------------------
    public void displayDate() {
    for (int x = 7; x < button.length; x++)
    button[x].setText("");
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMMM yyyy");
    java.util.Calendar cal = java.util.Calendar.getInstance();
    cal.set(year, month, 1);
    int dayOfWeek = cal.get(java.util.Calendar.DAY_OF_WEEK);
    int daysInMonth = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
    for (int x = 6 + dayOfWeek, day = 1; day <= daysInMonth; x++, day++)
    button[x].setText("" + day);
    l.setText(sdf.format(cal.getTime()));
    d.setTitle("Date Picker");

    }
        public void setDate(){
        SimpleDateFormat sdf = new SimpleDateFormat("dd-M-yyyy");
	String date = sdf.format(new Date());
        Rdate.setText(date);
    }
//------------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Product = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rdate = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Category = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rinput = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setText("Delete");
        jButton6.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton6.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton6.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 70, 50));

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("Date ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 80, 40));

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Home");
        jButton4.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton4.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton4.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 70, 50));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Clear");
        jButton1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 70, 50));

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton2.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton2.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 70, 50));

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Import");
        jButton3.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton3.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton3.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 70, 50));

        Product.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        Product.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ProductPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 150, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Product :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Price :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Category :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Total :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Quantity :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        Rdate.setEditable(false);
        Rdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(Rdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 150, 40));

        Total.setEditable(false);
        Total.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 150, 40));

        Quantity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuantityKeyPressed(evt);
            }
        });
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 150, 40));

        Price.setEditable(false);
        Price.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 150, 40));

        Category.setEditable(false);
        Category.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 150, 40));

        Rinput.setAutoCreateRowSorter(true);
        Rinput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Rinput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Category", "Quantity", "Price", "Total", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Rinput);
        if (Rinput.getColumnModel().getColumnCount() > 0) {
            Rinput.getColumnModel().getColumn(0).setResizable(false);
            Rinput.getColumnModel().getColumn(1).setResizable(false);
            Rinput.getColumnModel().getColumn(2).setResizable(false);
            Rinput.getColumnModel().getColumn(3).setResizable(false);
            Rinput.getColumnModel().getColumn(4).setResizable(false);
            Rinput.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 520, 560));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/vintage_paper.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProductPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ProductPopupMenuWillBecomeInvisible
        String Selected = (String) Product.getSelectedItem();
        String sqlQuery = "Select * from Bluebees where product=?";
        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.setString(1, Selected);
            rs = pst.executeQuery();
            if (rs.next()) {
                String ECategory = rs.getString("Category");
                Category.setText(ECategory);
                String EPrice = rs.getString("Price");
                Price.setText(EPrice);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    
    }//GEN-LAST:event_ProductPopupMenuWillBecomeInvisible

    private void QuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                double P = Double.parseDouble(Price.getText());
                double Q = Double.parseDouble(Quantity.getText());
                double T = P * Q;
                String Atotal = String.valueOf(T);
                Total.setText(Atotal);
            } catch (Exception a) {
                JOptionPane.showMessageDialog(null, a);
            }
        }
    }//GEN-LAST:event_QuantityKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login open = new Login();
        open.setVisible(true);
        open.Clear.setVisible(false);
        open.Login.setVisible(false);
        open.User.setVisible(false);
        open.Pass.setVisible(false);
        open.loginlabel1.setVisible(false);
        open.LoginLabel2.setVisible(false);
        open.loginPanel.setVisible(false);
        open.Logo.setVisible(false);

        open.Clear.setEnabled(false);
        open.Login.setEnabled(false);
        open.User.setEnabled(false);
        open.Pass.setEnabled(false);
        open.loginlabel1.setEnabled(false);
        open.LoginLabel2.setEnabled(false);
        open.loginPanel.setEnabled(false);
        open.Logo.setEnabled(false);

                   //inside
        open.Selection.setEnabled(true);
        open.Sales.setEnabled(true);
        open.Input.setEnabled(true);
        open.Worker.setEnabled(true);
        open.Record.setEnabled(true);
        open.MenuEdit.setEnabled(true);
        open.Logout.setEnabled(true);

        open.Selection.setVisible(true);
        open.Sales.setVisible(true);
        open.Input.setVisible(true);
        open.Worker.setVisible(true);
        open.Record.setVisible(true);
        open.MenuEdit.setVisible(true);
        open.Logout.setVisible(true);

//inside end
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {

        }
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JPanel p = new JPanel();
        final JFrame f = new JFrame();
        f.getContentPane().add(p);
        f.pack();
        f.setVisible(false);
        p.setVisible(false);
        Rdate.setText(new airasysad.DatePicker(f).setPickedDate());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
        Object[] row = new Object[6];
        DefaultTableModel model2 = (DefaultTableModel) Rinput.getModel();
        {
        if(!!Quantity.getText().isEmpty()  ){
            JOptionPane.showMessageDialog(null, "Insert Quantity Value");
                }
        if(!!Product.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "No Product Selected");
        }
        if(!!Rdate.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Date");
        }
         else
            {
            row[0] = Product.getSelectedItem().toString();
            row[1] = Category.getText();
            row[2] = Quantity.getText();
            row[3] = Price.getText();
            row[4] = Total.getText();   
            row[5] = Rdate.getText();
            model2.addRow(row);
        JOptionPane.showMessageDialog(null, "Added to list");
        //CLEAR-----
        Product.setSelectedItem("");
        Category.setText("");
        Quantity.setText("");
        Price.setText("");
        Total.setText("");
        Rdate.setText("");
                }
        }
}
catch(Exception e){}
finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //CLEAR-----
        Product.getSelectedItem().equals("");
        Category.setText("");
        Quantity.setText("");
        Price.setText("");
        Total.setText("");
        Rdate.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    DefaultTableModel model = (DefaultTableModel) Rinput.getModel();
    int[] rows = Rinput.getSelectedRows();
      try{
         if(Rinput.getSelectionModel().isSelectionEmpty()){
             JOptionPane.showMessageDialog(null, "No Item To Be Deleted From List");
         }
         else{
                for (int i = 0; i < rows.length; i++) {
                model.removeRow(rows[i] - i);
                }
         }
      }
      catch(Exception e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try{
     
 
        for (int x = 0; x < Rinput.getRowCount(); x++) {
        try {
        String sqlQuery = "insert into Sales (Product , Category ,  Quantity , Price , Total ,Date) values ('" + Rinput.getValueAt(x, 0).toString() + "','" + Rinput.getValueAt(x, 1).toString() + "','" + Rinput.getValueAt(x, 2).toString() + "','" + Rinput.getValueAt(x, 3).toString() + "','" + Rinput.getValueAt(x, 4).toString() + "','" + Rinput.getValueAt(x, 5).toString() + "')";
        pst = conn.prepareStatement(sqlQuery);
        pst.execute();   
                //                        Clear Tabe 
                Rinput.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Product", "Category", "Quantity", "Price", "Total", "Date"
                }
                ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
                });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
//        JOptionPane.showMessageDialog(null, "Saved to Sales");
        }
}
catch(Exception e){
 }
finally {
        try {
            
        rs.close();
        pst.close();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }
        }
  

 
 
 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField Category;
    private javax.swing.JTextField Price;
    private javax.swing.JComboBox Product;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Rdate;
    private javax.swing.JTable Rinput;
    private javax.swing.JTextField Total;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
