/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airasysad;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author takajima
 */
public class Login extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conn = database.sqliteConnect.connectorDB();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

//inside
        Selection.setEnabled(false);
        Sales.setEnabled(false);
        Input.setEnabled(false);
        Worker.setEnabled(false);
        Record.setEnabled(false);
        MenuEdit.setEnabled(false);
        Logout.setEnabled(false);

        Selection.setVisible(false);
        Sales.setVisible(false);
        Input.setVisible(false);
        Worker.setVisible(false);
        Record.setVisible(false);
        MenuEdit.setVisible(false);
        Logout.setVisible(false);

//inside end
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        MenuEdit = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginlabel1 = new javax.swing.JLabel();
        LoginLabel2 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Selection = new javax.swing.JPanel();
        Sales = new javax.swing.JButton();
        Input = new javax.swing.JButton();
        Worker = new javax.swing.JButton();
        Record = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Bluebees Logo1_1.jpg"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 710, 270));

        MenuEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MenuEdit.setText("Employee's And Admin");
        MenuEdit.setToolTipText("");
        MenuEdit.setMaximumSize(new java.awt.Dimension(128, 128));
        MenuEdit.setMinimumSize(new java.awt.Dimension(128, 128));
        MenuEdit.setPreferredSize(new java.awt.Dimension(128, 128));
        MenuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditActionPerformed(evt);
            }
        });
        getContentPane().add(MenuEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 180, 30));

        Logout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Logout.setText("Logout");
        Logout.setToolTipText("");
        Logout.setMaximumSize(new java.awt.Dimension(128, 128));
        Logout.setMinimumSize(new java.awt.Dimension(128, 128));
        Logout.setPreferredSize(new java.awt.Dimension(128, 128));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 180, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C: T.K.G 2016");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 565, 100, 20));

        loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        loginPanel.setOpaque(false);

        loginlabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        loginlabel1.setText("Username :");

        LoginLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LoginLabel2.setText("Password :");

        User.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserKeyPressed(evt);
            }
        });

        Pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassKeyPressed(evt);
            }
        });

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Login.setText("Login");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoginMouseReleased(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(255, 255, 255));
        Clear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginlabel1)
                            .addComponent(LoginLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pass)
                            .addComponent(User))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(0, 113, Short.MAX_VALUE)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginlabel1)
                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginLabel2)
                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        Selection.setOpaque(false);

        Sales.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sales.setText("Sales");
        Sales.setMaximumSize(new java.awt.Dimension(60, 60));
        Sales.setMinimumSize(new java.awt.Dimension(60, 60));
        Sales.setPreferredSize(new java.awt.Dimension(60, 60));
        Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesActionPerformed(evt);
            }
        });

        Input.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Input.setText("Sales Input");
        Input.setMaximumSize(new java.awt.Dimension(90, 60));
        Input.setMinimumSize(new java.awt.Dimension(90, 60));
        Input.setPreferredSize(new java.awt.Dimension(90, 60));
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        Worker.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Worker.setText("Employees Login System");
        Worker.setMaximumSize(new java.awt.Dimension(90, 60));
        Worker.setMinimumSize(new java.awt.Dimension(90, 60));
        Worker.setPreferredSize(new java.awt.Dimension(90, 60));
        Worker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerActionPerformed(evt);
            }
        });

        Record.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Record.setText("Employees Login Records");
        Record.setMaximumSize(new java.awt.Dimension(90, 60));
        Record.setMinimumSize(new java.awt.Dimension(90, 60));
        Record.setPreferredSize(new java.awt.Dimension(90, 60));
        Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectionLayout = new javax.swing.GroupLayout(Selection);
        Selection.setLayout(SelectionLayout);
        SelectionLayout.setHorizontalGroup(
            SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Input, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Worker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        SelectionLayout.setVerticalGroup(
            SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Worker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(Selection, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 180));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/vintage_paper.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void UserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserKeyPressed

    }//GEN-LAST:event_UserKeyPressed

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void PassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassKeyPressed

    }//GEN-LAST:event_PassKeyPressed

    private void LoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseReleased
        String sqlQuery = "select * from Administrator where username=? and password=?";
        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.setString(1, User.getText());
            pst.setString(2, Pass.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                Clear.setVisible(false);
                Login.setVisible(false);
                User.setVisible(false);
                Pass.setVisible(false);
                loginlabel1.setVisible(false);
                LoginLabel2.setVisible(false);
                loginPanel.setVisible(false);
                Logo.setVisible(false);

                Clear.setEnabled(false);
                Login.setEnabled(false);
                User.setEnabled(false);
                Pass.setEnabled(false);
                loginlabel1.setEnabled(false);
                LoginLabel2.setEnabled(false);
                loginPanel.setEnabled(false);
                Logo.setEnabled(false);

                   //inside
                Selection.setEnabled(true);
                Sales.setEnabled(true);
                Input.setEnabled(true);
                Worker.setEnabled(true);
                Record.setEnabled(true);
                MenuEdit.setEnabled(true);
                Logout.setEnabled(true);

                Selection.setVisible(true);
                Sales.setVisible(true);
                Input.setVisible(true);
                Worker.setVisible(true);
                Record.setVisible(true);
                MenuEdit.setVisible(true);
                Logout.setVisible(true);

//inside end
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect User or Password");
                User.setText("");
                Pass.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseReleased

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

    }//GEN-LAST:event_LoginActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        User.setText("");
        Pass.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesActionPerformed
        dispose();
        MenuFrame open = new MenuFrame();
        open.setVisible(true);
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_SalesActionPerformed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        dispose();
        Input open = new Input();
        open.setVisible(true);
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_InputActionPerformed

    private void WorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerActionPerformed
        dispose();
        Worker open = new Worker();
        open.setVisible(true);
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_WorkerActionPerformed

    private void RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordActionPerformed
        dispose();
        WorkersRecord open = new WorkersRecord();
        open.setVisible(true);
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_RecordActionPerformed

    private void MenuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditActionPerformed
        Configuration open = new Configuration();
        open.setVisible(true);
        MenuFrame Halt = new MenuFrame();
        Halt.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuEditActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Clear.setVisible(true);
        Login.setVisible(true);
        User.setVisible(true);
        Pass.setVisible(true);
        loginlabel1.setVisible(true);
        LoginLabel2.setVisible(true);
        loginPanel.setVisible(true);
        Logo.setVisible(true);

        Clear.setEnabled(true);
        Login.setEnabled(true);
        User.setEnabled(true);
        Pass.setEnabled(true);
        loginlabel1.setEnabled(true);
        LoginLabel2.setEnabled(true);
        loginPanel.setEnabled(true);
        Logo.setEnabled(true);

                   //inside
        Selection.setEnabled(false);
        Sales.setEnabled(false);
        Input.setEnabled(false);
        Worker.setEnabled(false);
        Record.setEnabled(false);
        MenuEdit.setEnabled(false);
        Logout.setEnabled(false);

        Selection.setVisible(false);
        Sales.setVisible(false);
        Input.setVisible(false);
        Worker.setVisible(false);
        Record.setVisible(false);
        MenuEdit.setVisible(false);
        Logout.setVisible(false);

//inside end
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    public javax.swing.JButton Clear;
    public javax.swing.JButton Input;
    public javax.swing.JButton Login;
    public javax.swing.JLabel LoginLabel2;
    public javax.swing.JLabel Logo;
    public javax.swing.JButton Logout;
    public javax.swing.JButton MenuEdit;
    public javax.swing.JPasswordField Pass;
    public javax.swing.JButton Record;
    public javax.swing.JButton Sales;
    public javax.swing.JPanel Selection;
    public javax.swing.JTextField User;
    public javax.swing.JButton Worker;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel loginPanel;
    public javax.swing.JLabel loginlabel1;
    // End of variables declaration//GEN-END:variables
}
