/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airasysad;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author takajima
 */
public class MenuFrame extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    //Date Picker SYSTEM -------
    int month = java.util.Calendar.getInstance().get(java.util.Calendar.MONTH);
    int year = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    JLabel l = new JLabel("", JLabel.CENTER);
    String day = "";
    JDialog d;
    JButton[] button = new JButton[49];

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        conn = database.sqliteConnect.connectorDB();
        TheTable();
        CurrentDate();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }
///DATE PICKER SYSTEM-----------------------------------------------------------

    public void displayDate() {
        for (int x = 7; x < button.length; x++) {
            button[x].setText("");
        }
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMMM yyyy");
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.set(year, month, 1);
        int dayOfWeek = cal.get(java.util.Calendar.DAY_OF_WEEK);
        int daysInMonth = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
        for (int x = 6 + dayOfWeek, day = 1; day <= daysInMonth; x++, day++) {
            button[x].setText("" + day);
        }
        l.setText(sdf.format(cal.getTime()));
        d.setTitle("Date Picker");

    }

    public void TheTable() {
        try {
            String sqlQuery = " SELECT DISTINCT Date,sum(total) AS 'total',product,category,sum(quantity) as 'quantity' from sales group by product ";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            thisTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }

    public void toExcel(JTable table, File file) {
        try {
            TableModel model = thisTable.getModel();
            try (FileWriter excel = new FileWriter(file)) {

                for (int i = 0; i < model.getColumnCount(); i++) {
                    excel.write(model.getColumnName(i) + ",");
                }

                excel.write("\n");

                for (int i = 0; i < model.getRowCount(); i++) {
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        //  System.out.println(model.getValueAt(i, j).toString());
                        excel.write(model.getValueAt(i, j).toString() + ",");
                    }
                    excel.write("\n");
                }
            }

        } catch (IOException e) {
        }
    }

    public void CurrentDate() {
        DecimalFormat mFormat = new DecimalFormat("00");
        mFormat.format(Double.valueOf(year));
        Calendar cal = new GregorianCalendar();
        int mm = cal.get(Calendar.MONTH);
        int yyyy = cal.get(Calendar.YEAR);
        int dd = cal.get(Calendar.DAY_OF_MONTH);
        From.setText("" + dd + '-' + mFormat.format(Double.valueOf(mm + 1)) + '-' + yyyy);
        To.setText("" + dd + '-' + mFormat.format(Double.valueOf(mm + 1)) + '-' + yyyy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        export = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        From = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        Dfrom = new javax.swing.JButton();
        Dto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        thisTable = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        export.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        export.setText("Export");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        getContentPane().add(export, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 50));

        Home.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Home.setText("Home");
        Home.setMaximumSize(new java.awt.Dimension(60, 60));
        Home.setMinimumSize(new java.awt.Dimension(60, 60));
        Home.setPreferredSize(new java.awt.Dimension(60, 60));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 70, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Search :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 50, 50));

        Search.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Search.setText("Search");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SearchMouseReleased(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchKeyPressed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 140, 30));

        From.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 160, 30));

        To.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, 30));

        Dfrom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dfrom.setText("Latest Date");
        Dfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DfromActionPerformed(evt);
            }
        });
        getContentPane().add(Dfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        Dto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dto.setText("Past Date");
        Dto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtoActionPerformed(evt);
            }
        });
        getContentPane().add(Dto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 30));

        thisTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        thisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(thisTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 740, 450));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/vintage_paper.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed

        Login open = new Login();
        open.setVisible(true);
        open.Clear.setVisible(false);
        open.Login.setVisible(false);
        open.User.setVisible(false);
        open.Pass.setVisible(false);
        open.loginlabel1.setVisible(false);
        open.LoginLabel2.setVisible(false);
        open.loginPanel.setVisible(false);
        open.Logo.setVisible(false);

        open.Clear.setEnabled(false);
        open.Login.setEnabled(false);
        open.User.setEnabled(false);
        open.Pass.setEnabled(false);
        open.loginlabel1.setEnabled(false);
        open.LoginLabel2.setEnabled(false);
        open.loginPanel.setEnabled(false);
        open.Logo.setEnabled(false);

                   //inside
        open.Selection.setEnabled(true);
        open.Sales.setEnabled(true);
        open.Input.setEnabled(true);
        open.Worker.setEnabled(true);
        open.Record.setEnabled(true);
        open.MenuEdit.setEnabled(true);
        open.Logout.setEnabled(true);

        open.Selection.setVisible(true);
        open.Sales.setVisible(true);
        open.Input.setVisible(true);
        open.Worker.setVisible(true);
        open.Record.setVisible(true);
        open.MenuEdit.setVisible(true);
        open.Logout.setVisible(true);

//inside end
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {

        }
        dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void DfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DfromActionPerformed
        JPanel p = new JPanel();
        final JFrame f = new JFrame();
        f.getContentPane().add(p);
        f.pack();
        f.setVisible(false);
        p.setVisible(false);
        From.setText(new DatePicker(f).setPickedDate());

        try {
            //String sqlQuery = "SELECT * FROM sales WHERE date BETWEEN '" + Dto.getText() + "'  AND '" + Dfrom.getText() + "' group by product  ";
            String sqlQuery = "SELECT DISTINCT Date,sum(total) AS 'total',product,category,sum(quantity) as 'quantity' from sales WHERE date BETWEEN  '" + To.getText().toString() + "' AND '" + From.getText().toString() + "' group by product";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            thisTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_DfromActionPerformed

    private void DtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtoActionPerformed
        JPanel p = new JPanel();
        final JFrame f = new JFrame();
        f.getContentPane().add(p);
        f.pack();
        f.setVisible(false);
        p.setVisible(false);
        To.setText(new DatePicker(f).setPickedDate());

        try {
            //String sqlQuery = "SELECT * FROM sales WHERE date BETWEEN '" + Dto.getText() + "'  AND '" + Dfrom.getText() + "' group by product  ";
            String sqlQuery = "SELECT DISTINCT Date,sum(total) AS 'total',product,category,sum(quantity) as 'quantity' from sales WHERE date BETWEEN  '" + To.getText().toString() + "' AND '" + From.getText().toString() + "' group by product";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            thisTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_DtoActionPerformed

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed
        String Product = Search.getText();
        try {
            String sqlQuery = " SELECT DISTINCT Date,sum(total) AS 'total',product,category,sum(quantity) as 'quantity' from sales where product like '%" + Product + "%'group by product ";
            // String sqlQuery = "Select * from Inventory where product like '%" + Product + "%'";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            thisTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_SearchKeyPressed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Data on the table will be only exported", "Export", JOptionPane.YES_NO_OPTION);

        if (p == 0) {
            String filedir = "Total Sales From '" + From.getText().toString() + "' to '" + To.getText().toString() + "'.csv";
            File desktop = new File(System.getProperty("user.home"), "Desktop");;
            File file = new File(desktop, filedir);
            toExcel(thisTable, file);
            JOptionPane.showMessageDialog(null, "File Saved");
        } else {
            JOptionPane.showMessageDialog(null, "Export canceled");
        }


    }//GEN-LAST:event_exportActionPerformed

    private void SearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseReleased
        Search.setText("");
    }//GEN-LAST:event_SearchMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Dfrom;
    private javax.swing.JButton Dto;
    private javax.swing.JLabel From;
    private javax.swing.JButton Home;
    private javax.swing.JTextField Search;
    private javax.swing.JLabel To;
    private javax.swing.JButton export;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable thisTable;
    // End of variables declaration//GEN-END:variables
}
